name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Tokyo

jobs:
  yt-dlp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip3 install yt-dlp yt-dlp-rajiko

      - name: Test of yt-dlp
        run: yt-dlp wv+wa 'https://tver.jp/episodes/epc1y4j686'

      - name: Collect
        run: |
          mkdir -p dl
          mv *.{m4a,mp4} dl/ || true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: dl/
