name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Tokyo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Collect
        run: |
          mkdir -p radiko
          echo "Hello world" > radiko/sample.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SAVING_KEY }}

      - name: Save from Google Drive
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_MYDRIVE_TYPE: drive
          RCLONE_CONFIG_MYDRIVE_SCOPE: drive
          RCLONE_CONFIG_MYDRIVE_ROOT_FOLDER_ID: '17wZ5CRm5T1Fgfk3rtzyzO2EcBTUluzZr'
          RCLONE_CONFIG_MYDRIVE_SERVICE_ACCOUNT_BLANK: true
        with:
          args: "copy radiko/ mydrive:"
